version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: src/MixWarz.API/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=MixWarz;Username=postgres;Password=postgres;
      - Jwt__Key=DockerComposeJwtKeyForDevelopmentOnly
      - Jwt__Issuer=MixWarz.Docker
      - Jwt__Audience=MixWarzApp.Docker
      - Jwt__ExpiryInDays=7
    depends_on:
      - postgres
      - redis
    networks:
      - mixwarz-network
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  postgres:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=MixWarz
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mixwarz-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - mixwarz-network
    volumes:
      - redis-data:/data

networks:
  mixwarz-network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
