// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MixWarz.Infrastructure.Persistence;

#nullable disable

namespace MixWarz.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250517000000_AddMultitrackZipUrlToCompetition")]
    partial class AddMultitrackZipUrlToCompetition
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            // This is a placeholder for the model snapshot
            // The actual model will be taken from the database when the migration is applied
#pragma warning restore 612, 618
        }
    }
}